# Generated by Django 3.2.13 on 2022-06-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0003_rename_create_by_event_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='create_by',
        ),
    ]
