# Generated by Django 3.2.13 on 2022-06-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0004_rename_created_by_event_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
