# Generated by Django 4.0.3 on 2022-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceITSV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
