# Generated by Django 4.0.3 on 2022-03-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceITSV', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
