# Generated by Django 4.0.3 on 2022-03-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceITSV', '0005_ppp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Ppp',
        ),
    ]
