# Generated by Django 4.0.3 on 2022-03-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceITSV', '0007_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
