# Generated by Django 4.0.3 on 2022-04-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceITSV', '0010_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
